// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOtw6hjpCxNYYMYOGBcx3CzzM7Hct7qVY',
    appId: '1:154409842653:web:b22416686105d64eaf6834',
    messagingSenderId: '154409842653',
    projectId: 'pistagram-f2300',
    authDomain: 'pistagram-f2300.firebaseapp.com',
    databaseURL: 'https://pistagram-f2300-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pistagram-f2300.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKA-59h8sltFzMd5TNTXe9j8VrcsD_fu8',
    appId: '1:154409842653:android:34ebfdfc36700ed5af6834',
    messagingSenderId: '154409842653',
    projectId: 'pistagram-f2300',
    databaseURL: 'https://pistagram-f2300-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pistagram-f2300.appspot.com',
  );
}
